MovieLib/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieLib.Models
{
    public class Movie
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required(ErrorMessage = "Put the name of film")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Put the origin of film")]
        public string Country { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }

        public Movie(string Name, string Country, DateTime ReleaseDate)
        {
            this.Name = Name;
            this.Country = Country;
            this.ReleaseDate = ReleaseDate;
        }

        public Movie(int Id,string Name, string Country, DateTime ReleaseDate)
        {
            this.Id = Id;
            this.Name = Name;
            this.Country = Country;
            this.ReleaseDate = ReleaseDate;
        }

        public Movie() { }
    }
}

MovieLib/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MovieLib.Repository;
using MovieLib.Models;


namespace MovieLib.Controllers
{
    public class MovieController : Controller
    {
        private IMovie movieRepo;

        public MovieController()
        {
            movieRepo = new MovieRepository();
        }

        public MovieController(IMovie repo)
        {
            movieRepo = repo;
        }
        
        //
        // GET: /Movies/

        [Authorize]
        public ActionResult Index()
        {
            var list = movieRepo.GetMovies().ToList();
            return View(list);
        }

        public ActionResult Find(string term)
        {
            var list = movieRepo.GetMovies(term).ToList();
            return View(list);
        }

        //
        // GET: /Movie/Create
        [Authorize]
        public ActionResult Create()
        {
            return View(new Movie());
        }

        //
        // POST: /Movie/Create

        [HttpPost]
        public ActionResult Create(Movie item)
        {
            try
            {
                var movie = new Movie();
                movie.Name = item.Name;
                movie.Country = item.Country;
                movie.ReleaseDate = item.ReleaseDate;
                movieRepo.AddMovie(movie);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Movie/Edit/5

        public ActionResult Edit(int id)
        {
            var item = movieRepo.GetMovie(id);
            var movie = new Movie();
            movie.Id = id;
            movie.Name = item.Name;
            movie.Country = item.Country;
            movie.ReleaseDate = item.ReleaseDate;
            return View(movie);
        }

        //
        // POST: /Movie/Edit/5

        [HttpPost]
        public ActionResult Edit(Movie movie)
        {
            try
            {
                movieRepo.UpdateMovie(movie);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Movie/Delete/5

        public ActionResult Delete(int id)
        {
            var movie = movieRepo.GetMovie(id);
            return View(movie);
        }

        //
        // POST: /Movie/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                movieRepo.DeleteMovie(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MovieLib/Controllers/SPAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MovieLib.Models;
using MovieLib.Repository;
using System.Diagnostics;

namespace MovieLib.Controllers
{
    public class SPAController : Controller
    {
        private IMovie movieRepo;

        public SPAController()
        {
            movieRepo = new MovieRepository();
        }
        
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /SPA/

        public ActionResult GetAll()
        {
            var list = movieRepo.GetMovies().ToList();
            return PartialView("_GetAll",list);
        }

        public ActionResult Find(string term)
        {
            var list = movieRepo.GetMovies(term).ToList();
            return PartialView("_Find",list);
        }

        //
        // GET: /SPA/Create

        public ActionResult Create()
        {
            return PartialView("_Create",new Movie());
        }

        //
        // POST: /SPA/Create

        [HttpPost]
        public ActionResult Create(Movie item)
        {
            try
            {
                var movie = new Movie();
                movie.Name = item.Name;
                movie.Country = item.Country;
                movie.ReleaseDate = item.ReleaseDate;
                movieRepo.AddMovie(movie);
                return Content("New Movie Created");
            }
            catch
            {
                return Content("Check errors in New Movie Form ");
            }
        }

        //
        // GET: /SPA/Edit/5

        public PartialViewResult Edit(int id)
        {
            var item = movieRepo.GetMovie(id);
            var movie = new Movie();
            movie.Id = id;
            movie.Name = item.Name;
            movie.Country = item.Country;
            movie.ReleaseDate = item.ReleaseDate;
            return PartialView("_Edit", movie);
        }

        //
        // POST: /SPA/Edit/5

        [HttpPost]
        public ActionResult Edit2(Movie movie)
        {
            try
            {
                
                movieRepo.UpdateMovie(movie);
                return PartialView("_Update");
            }
            catch
            {
                return Content("Not correct values: \n Check Editing fields");
            }
        }

        //
        // GET: /SPA/Delete/5

        public PartialViewResult Delete(int id)
        {
            var movie = movieRepo.GetMovie(id);
            return PartialView("_Delete",movie);
        }

        //
        // POST: /SPA/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                movieRepo.DeleteMovie(id);
                return PartialView("_DeletePost");
            }
            catch
            {
                return Content("There is no such movie");
            }
        }

    }
}

MovieLib/Views/Movie/Create.cshtml
@model MovieLib.Models.Movie
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Movie</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Country)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ReleaseDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ReleaseDate)
                @Html.ValidationMessageFor(model => model.ReleaseDate)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MovieLib/Views/Movie/Delete.cshtml
@model MovieLib.Models.Movie
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete movie?</h3>
    <fieldset>
        <legend>Movie</legend>

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Country)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Country)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.ReleaseDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ReleaseDate)
        </div>
    </fieldset>
    @using (Html.BeginForm()) {
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }

</body>
</html>

MovieLib/Views/Movie/Edit.cshtml
@model MovieLib.Models.Movie
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Movie</legend>
    
            @Html.HiddenFor(model => model.Id)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Country)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ReleaseDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ReleaseDate)
                @Html.ValidationMessageFor(model => model.ReleaseDate)
            </div>
    
            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MovieLib/Views/Movie/Find.cshtml
@model IEnumerable<MovieLib.Models.Movie>
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Found movies</title>
</head>
<body>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
    <div>
        @Html.ActionLink("Back to Main Page", "Index")
    </div>
</body>
</html>

MovieLib/Views/Movie/Index.cshtml
@model IEnumerable<MovieLib.Models.Movie>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    Welcome @HttpContext.Current.User.Identity.Name
    @if (Request.IsAuthenticated)
       {  
        using (Html.BeginForm("Logout","User", FormMethod.Post, new { id="logoutForm"}))
    {
        <a href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
    }
       }
    <br />
    @Html.ActionLink("Go SPA View", "Index", "SPA")
    <br />
    <p>
        @Html.ActionLink("Add Movie", "Create")
    </p>
    @using (Html.BeginForm("Find","Movie",
        FormMethod.Post))
    {
        <input type="text" name="term" id="term" />
        <input type="submit" value="Find a Movie" />
    }
    <br/>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>